In [1]:
import pandas as pd
import pyarrow as pv
import os
from google.cloud import storage
# Only need this if you're running this code locally.
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r'../.google/credentials/google_credentials.json'

In [2]:
client = storage.Client()
bucket_dtc = client.get_bucket('dtc_data_lake_de-zoomcamp-356807')
bucket_nyc = client.get_bucket('nyc-tlc-backup')

In [3]:
df = pd.read_csv("gs://nyc-tlc-backup/yellow_tripdata_2019-01.csv", encoding = "ISO-8859-1",low_memory=False)
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-01-01 00:46:40,2019-01-01 00:53:20,1,1.50,1,N,151,239,1,7.0,0.5,0.5,1.65,0.0,0.3,9.95,NaN
1,1,2019-01-01 00:59:47,2019-01-01 01:18:59,1,2.60,1,N,239,246,1,14.0,0.5,0.5,1.00,0.0,0.3,16.30,NaN
2,2,2018-12-21 13:48:30,2018-12-21 13:52:40,3,0.00,1,N,236,236,1,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN
3,2,2018-11-28 15:52:25,2018-11-28 15:55:45,5,0.00,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,7.55,NaN
4,2,2018-11-28 15:56:57,2018-11-28 15:58:33,5,0.00,2,N,193,193,2,52.0,0.0,0.5,0.00,0.0,0.3,55.55,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7667787,2,2019-01-31 23:57:36,2019-02-01 00:18:39,1,4.79,1,N,263,4,1,18.0,0.5,0.5,3.86,0.0,0.3,23.16,0.0
7667788,2,2019-01-31 23:32:03,2019-01-31 23:33:11,1,0.00,1,N,193,193,1,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0
7667789,2,2019-01-31 23:36:36,2019-01-31 23:36:40,1,0.00,1,N,264,264,1,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0
7667790,2,2019-01-31 23:14:53,2019-01-31 23:15:20,1,0.00,1,N,264,7,1,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0
7667791,2,2019-01-31 23:12:49,2019-01-31 23:14:08,1,0.00,1,N,193,193,1,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0

In [4]:
df.dtypes

VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count            int64
trip_distance            float64
RatecodeID                 int64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [6]:
a = df['VendorID'].unique()                    
b = df['tpep_pickup_datetime'].unique()      
c = df['tpep_dropoff_datetime'].unique()     
d = df['passenger_count'].unique()        
e = df['trip_distance'].unique()                 
f = df['RatecodeID'].unique()               
g = df['store_and_fwd_flag'].unique()               
h = df['PULocationID'].unique()            
i = df['DOLocationID'].unique()            
j = df['payment_type'].unique()              
k = df['fare_amount'].unique()                    
l = df['extra'].unique()                  
m = df['mta_tax'].unique()               
n = df['tip_amount'].unique()             
o = df['tolls_amount'].unique()                
p = df['improvement_surcharge'].unique()    
q = df['total_amount'].unique()             
r = df['congestion_surcharge'].unique()

In [7]:
print('VendorID',a)
print('tpep_pickup_datetime',b)
print('tpep_dropoff_datetime',c)
print('passenger_count',d)
print('trip_distance',e)
print('RatecodeID',f)
print('store_and_fwd_flag',g)
print('PULocationID',h)
print('DOLocationID',i)
print('payment_type',j)
print('fare_amount',k)
print('extra',l)
print('mta_tax',m)
print('tip_amount',n)
print('tolls_amount',o)
print('improvement_surcharge',p)
print('total_amount',q)
print('congestion_surcharge',r)

VendorID [1 2 4]
tpep_pickup_datetime ['2019-01-01 00:46:40' '2019-01-01 00:59:47' '2018-12-21 13:48:30' ...
 '2019-01-31 23:57:53' '2019-01-31 23:58:38' '2019-01-31 23:54:41']
tpep_dropoff_datetime ['2019-01-01 00:53:20' '2019-01-01 01:18:59' '2018-12-21 13:52:40' ...
 '2019-02-01 00:16:18' '2019-02-01 00:30:41' '2019-02-01 00:18:39']
passenger_count [1 3 5 2 4 0 6 8 7 9]
trip_distance [ 1.5   2.6   0.   ... 29.63 33.12 44.81]
RatecodeID [ 1  2  4  5  3 99  6]
store_and_fwd_flag ['N' 'Y']
PULocationID [151 239 236 193 163 229 141 246 238 224 170 107  41 116 113 161 138 144
 231 237 263 132 264 142 249 137  90 162 140  68  88  74  79  75 233 148
  48 143   4 164 232  45  43 186 158  50 114  42  14  11 181 211  13 261
  97 234 125 145 262 226  24 166  80 189  33 100 126 159 244 243 209  87
  25 260 223 196 152 230   7  66 228 235 265 134  65 129  82 195 255 179
 169  89  37  17 225  12  52 112 256  61 257 215  70 217 177  49 168  76
 133 198  40 247 254 216  77 250 119 106 208  60 146 191  54 205  36 153
  34  78 130 241  69 124 190 203  19 213  10 218 174 248 222 157 160 188
  93 123  39  63  21  94 127  51  20  18 122  35  56 259 202  71  92 197
 136  62  83   8 120 220  95 173 165  81 227 128  67 183  16 147 201 167
 210  28 212  85  22  91  64  38  72  47  29 149 150 178 101   1 155 258
  98  32 221 171  23 242 192 187 182 180 185 121  96  26  57 131 109 108
 200 194  53  59 135 139 219   6 117 102   3  15  44  55  73 154 207  86
  46 251 252 111 240   9 253 115  58   5 175  31 184 245  30 118 156   2
 206 214 172 105  84 204  27  99 176 104 199]
DOLocationID [239 246 236 193 229   7 234 162 151  25 170 107 141 247  42  90  50 261
  79 181 264 142 238  83 263 140 161 137 243  75  41  88 168 113  68 224
 112  48 233 249  13   4 262 148 232  97 256 186 143 145  43  87 198  98
 228  22 237 223 231 164 158 244 255  35 257  37  82 146  74 125 138  92
 226  24 114  14  33  95 152 225 216 218 129 213  18 163  52  80 100 144
  36 202  16 188 209 166 265 235  49  66 180 106  40 189 250 116  61 196
 173 119 230 212 211 122 133  10 136  51  28 147 165  45  12 259 241 197
 260 215 159  54 130  63  73  85 220  17 167  89 127 217  71 219 123 134
  78 135 101 121 177  69 169  70  65  47 200  76  26 149 185  57 227 160
  56  29  67  11  32 179  39  60 132 222  62 203 190  53 248 126 201  38
 182 184 157  94  86 208 171  55 102  21  91  15  72   1 174  31  19 194
 150  77 120 205 242  93 254  96 210 139 252 183 108 131  20 117 258 156
 118   9 111 195 155  34 153 124  81  23 240 178 115  64   6 154 221 191
   3 206 245 109 176  58 128 204   8 251  44 175 192  46 172 207  84  59
  30 187   5 214 253  27 105  99   2]
payment_type [1 2 4 3]
fare_amount [  7.    14.     4.5  ... 144.6   65.3   11.46]
extra [ 5.0000e-01  0.0000e+00 -5.0000e-01  3.0000e+00  1.0000e+00 -1.0000e+00
  1.3000e+00  8.0000e-01  2.5000e+00  1.7500e+01  4.5000e+00  1.8500e+01
 -4.5000e+00  1.8000e+01  5.3000e+00  1.8000e+00  3.5000e+00 -2.5000e+00
  1.1000e+00  3.0000e-01  2.0000e-01 -3.1730e+01 -1.7000e+01  2.5000e-01
  1.5000e+00  2.3000e+00 -6.0000e+01  7.0000e-01  1.0900e+01  4.5000e-01
  5.3538e+02 -4.0000e-01 -3.6710e+01  9.5000e-01  1.1000e-01 -4.9000e-01
  2.3040e+01]
mta_tax [ 0.5  -0.5   0.    0.9   0.25 32.53 18.3  60.8   0.35  2.42  1.   37.51]
tip_amount [ 1.65  1.    0.   ... 35.58 58.56 30.19]
tolls_amount [ 0.0000e+00  5.7600e+00  5.6000e-01  1.1520e+01  2.6400e+00  1.0500e+01
  5.2800e+00  7.9200e+00  1.3500e+01  2.1000e+01  2.1600e+00  1.8100e+01
  6.0000e+00  1.7280e+01  1.6500e+01  2.1260e+01  1.2500e+01  2.5400e+00
  1.5900e+01  3.1610e+01  5.5400e+00  2.0000e+01  1.0080e+01  5.0000e+00
  5.1200e+01  3.2500e+01  5.5600e+00  1.7000e+01  5.7000e+00  2.4500e+00
  1.3200e+01  1.5000e+01  1.6260e+01  5.7500e+00  9.0000e-02  1.3830e+01
  1.9000e+01  1.5600e+01  2.2000e+01  2.3040e+01  1.0000e+01  2.5000e+01
  1.6000e+01  1.8000e+01  3.0000e+00  7.5000e+01  1.4800e+01  1.3900e+01
  2.2500e+01  5.5000e+00  1.6040e+01  1.5500e+01  5.8500e+00  1.8500e+01
  1.5400e+01  1.5470e+01  2.5500e+01  1.2660e+01  1.4500e+01  1.7100e+01
  1.4750e+01  8.5000e+00  1.7500e+01  1.8400e+01  1.5250e+01  2.8000e+01
  2.7500e+01  5.7800e+00  1.7200e+01  1.8700e+01  1.4650e+01  5.7300e+00
  1.4950e+01  2.4260e+01  1.1500e+01  1.7400e+01  1.7300e+01  1.9500e+01
  1.8260e+01  3.6520e+01  2.2300e+01  1.5100e+01 -5.7600e+00  6.8800e+00
  2.0500e+01  2.6760e+01  2.3520e+01  2.4020e+01  2.2020e+01  5.3300e+00
  1.6750e+01  6.7600e+00  1.5450e+01  2.1250e+01  2.0600e+01  4.6200e+00
  8.0000e+00  6.5600e+00  8.4000e+00  1.3560e+01  1.1760e+01  1.7700e+01
  1.5300e+01  1.6050e+01 -1.0500e+01  1.3250e+01  2.3700e+01  1.6250e+01
  1.7800e+01  1.8600e+01  1.5800e+01  3.0000e+01  3.2520e+01  1.3700e+01
  1.5700e+01  1.2950e+01  2.0450e+01  9.0600e+00  1.7570e+01  7.4200e+00
  3.4000e+01  1.6300e+01  5.7900e+00  1.3000e+01  1.6550e+01  5.6500e+00
  1.6170e+01  2.7020e+01  7.5100e+00  1.6800e+01  2.8000e+00  5.5700e+00
  5.9000e+00  1.2650e+01  2.0300e+01  1.9250e+01  5.7400e+00  1.3050e+01
  1.8450e+01  1.7760e+01  1.6490e+01  1.6700e+01  8.8800e+00  1.7490e+01
  5.4600e+00  4.3200e+00  2.4790e+01  3.1500e+01  2.2700e+01  1.2760e+01
  4.6020e+01  1.7250e+01  2.9220e+01  1.4660e+01  2.9020e+01  1.0260e+01
  1.0760e+01  2.3810e+01  1.4850e+01  4.3500e+01  2.6260e+01  9.7600e+00
  3.6250e+02  1.4000e+01  7.7600e+00  1.4700e+01  1.1490e+01  7.5600e+00
  1.2600e+00  1.0000e+00  7.0000e+00  3.0420e+01  6.5000e+01  1.9060e+01
  1.6560e+01  1.5640e+01  2.1520e+01  1.2700e+01  1.5750e+01  1.5780e+01
  1.8750e+01  1.5380e+01  1.0550e+01  7.5000e+00  1.4260e+01  2.2520e+01
  1.4600e+01  1.2000e+01  5.9200e+00  1.8300e+01  1.8800e+01  7.9900e+00
  5.6400e+00  1.6900e+01  1.5760e+01  5.7700e+00 -2.1000e+01  5.6700e+00
  1.5200e+01  1.3260e+01  1.7850e+01  2.3970e+01  1.7750e+01  2.5450e+01
  2.3500e+01  3.7020e+01  4.0000e+00  2.5620e+01  1.9300e+01  1.9400e+01
  2.0400e+01  1.1260e+01  4.4000e+01  5.6600e+00  2.6000e+01  1.3100e+01
  2.7470e+01  7.0000e-02  1.5890e+01  1.5490e+01  1.9260e+01  2.2200e+01
  1.2600e+01  3.0020e+01  1.1750e+01  1.7260e+01  2.8520e+01  1.1410e+01
  2.6660e+01  2.4500e+01  3.7500e+01  2.0900e+01  1.1000e+01  5.4400e+00
  1.2850e+01  1.3150e+01 -1.0000e+00  1.4100e+01  1.5580e+01  4.6000e+00
  1.2300e+01  4.8000e+00  1.0155e+02  5.7600e+02  1.3270e+01  1.3140e+01
  2.3000e+01  4.4800e+01  1.8550e+01  1.7380e+01  1.3680e+01  4.2500e+00
  4.7000e+01  1.1700e+01  1.6400e+01  1.3760e+01  8.1400e+00  1.2500e+00
  1.2150e+01  6.5000e+00  8.2500e+00  1.6100e+01  2.1500e+01  1.3400e+01
  1.2800e+01  7.2000e+00  1.2320e+01  1.4900e+01  5.5500e+00  2.1800e+01
  8.7600e+00  1.8900e+01  1.8560e+01  2.5000e+00  2.0000e+00  9.0000e+00
  2.8020e+01  1.1460e+01  2.1400e+01  1.5540e+01  3.4020e+01  5.0000e-01
  5.1800e+00  1.5740e+01  2.7900e+01  1.5000e+00  4.5000e+00  2.8250e+01
  2.3030e+01  3.7500e+00  1.2100e+01  3.3000e+01  1.8380e+01  5.7647e+02
  2.1100e+01  2.6000e+00  1.5140e+01  2.6020e+01  1.2900e+01  1.5410e+01
  1.8020e+01  2.4000e+00  5.7200e+00  5.2600e+00  1.4820e+01  2.9520e+01
  2.6520e+01  1.4250e+01  5.6000e+00  2.7500e+00  2.7600e+00  6.9500e+00
  5.1400e+00  4.3260e+01 -2.6400e+00  3.0760e+01  3.5000e+00  2.5760e+01
  9.5760e+01  1.5150e+01  1.0060e+01  9.7000e+01  2.2500e+00  1.7500e+00
  1.3300e+01  1.9900e+01  6.5200e+00  2.7770e+01  1.2750e+01  1.4520e+01
  1.9700e+01  1.7450e+01  4.6260e+01  1.1080e+01  2.3050e+01  2.8820e+01
  1.8250e+01  1.6760e+01  2.4900e+00  5.2000e+00  1.6990e+01  2.0760e+01
  6.5700e+00  3.1020e+01  5.5900e+00  1.0000e+02  3.0500e+01  8.3600e+00
  5.0500e+01  1.1300e+01  1.9200e+01  5.4900e+00  1.3750e+01  1.8040e+01
  2.2800e+01  2.1160e+01  1.6020e+01  1.0570e+01  6.7500e+00  1.9050e+01
  5.1200e+00  1.8760e+01 -1.7000e+01  1.5120e+01  1.5550e+01  2.6180e+01
  2.5020e+01  3.2000e+01  1.7160e+01  8.2000e+00  1.5350e+01  9.2600e+00
  6.8000e+00  2.7160e+01  9.2000e+00  2.7000e+01  1.5000e-01  2.8900e+01
  2.2760e+01  1.9850e+01  1.2520e+01  2.2860e+01  5.2700e+00  5.0760e+02
  4.0000e+01  6.2400e+00  1.8850e+01  4.5700e+00  2.1010e+01  5.3900e+00
  2.6470e+01  2.3260e+01  1.0850e+01  3.3020e+01  3.2020e+01  2.6500e+01
  4.5000e+01  4.6000e+01  1.4300e+01  3.9020e+01  9.5600e+00  2.8260e+01
  1.5840e+01  8.5500e+00  1.6600e+00  2.9000e+01  1.9650e+01  9.7000e+00
  2.6770e+01  1.0000e-02  2.8800e+01  1.5370e+01  2.4600e+00  2.9700e+01
  1.4880e+01  1.6290e+01  2.5600e+00  2.6500e+00  3.5000e+01  1.7050e+01
  1.9800e+01  1.1310e+01  5.6800e+00  8.2600e+00  2.0000e-02  3.7000e+00
  7.6576e+02  1.6620e+01  3.1000e+01  2.8320e+01  1.2240e+01  2.5260e+01
  5.0000e+01  7.9400e+00  5.5000e+01  4.1600e+00  3.6000e+01  1.0590e+01
  1.7680e+01  9.7020e+01  1.6880e+01  5.2200e+00  8.8000e+00  6.6000e+01
  5.4700e+00  8.0800e+00  3.1200e+01  2.1060e+01  3.8760e+01  5.1000e+00
  1.5950e+01  1.8420e+01  6.3300e+00  1.1430e+01  2.9620e+01  3.8300e+00
  4.5500e+01  7.0100e+00  2.0200e+01  2.8490e+01  5.8000e+00  2.0700e+01
  3.1750e+01  7.5200e+00  1.5680e+01  4.9000e+00  2.0800e+01  7.2600e+00
  1.6820e+01  1.7470e+01  3.1760e+01  1.0300e+01  2.6490e+01  1.3650e+01
  1.3970e+01  1.5830e+01  1.6950e+01  5.8700e+00  1.4200e+01  1.9750e+01
  1.8350e+01  4.3520e+01  1.2980e+01  2.4000e+01  2.7070e+01  1.0420e+01
  5.6000e+01  2.6400e+01  2.2260e+01  7.4000e+00  2.4270e+01  2.3200e+01
  1.7900e+01  1.4990e+01  1.7350e+01  2.6600e+00  1.9100e+01  5.9600e+00
  1.7820e+01  9.5000e+00  5.8600e+00  4.9040e+01  1.6600e+01  2.2600e+00
  1.7080e+01  5.4000e+00  2.0560e+01  5.0000e-02  3.0000e-01  6.4600e+00
  2.7220e+01  8.0500e+01  3.2700e+00  1.5050e+01  1.3450e+01  1.0450e+01
  2.3250e+01  2.1210e+01  1.3800e+01  6.2600e+00  1.0510e+02  6.2000e+00
  2.6670e+01  1.1510e+01  2.3000e-01  9.9600e+00  3.3520e+01  5.7000e+01
  1.5040e+01  1.5650e+01  2.6700e+00  3.0260e+01  1.7420e+01  1.0340e+01
  1.1600e+02  1.2830e+01  1.9920e+01  1.0160e+01  9.8000e+00  3.3260e+01
  5.9800e+00  5.8400e+00  7.1260e+01 -1.4000e+01  1.5160e+01  1.4150e+01
  1.2260e+01  1.9600e+01  1.7600e+01  2.0850e+01  1.7650e+01  5.7600e+01
  1.9080e+01  4.4500e+01  5.1716e+02  1.4020e+01  4.2020e+01  1.6510e+01
  1.7270e+01  2.3750e+01  1.6960e+01  5.0796e+02  4.5760e+01  5.5200e+00
  1.6450e+01 -1.6260e+01  4.1200e+00  4.6600e+01  7.4132e+02  2.2040e+01
  2.1140e+01  6.9300e+00  2.7450e+01  3.5870e+01  1.6890e+01  1.4400e+01
  1.3770e+01  2.0260e+01  1.5520e+01  8.9800e+00  2.0050e+01  2.6380e+01
  1.0152e+02  6.7700e+00  1.0167e+02  3.3000e+00  1.3570e+01  1.7150e+01
  2.7620e+01  8.5750e+01  8.0000e-02  1.3550e+01  1.5980e+01  1.5940e+01
  4.6600e+00  2.5900e+00  1.5770e+01  1.7320e+01  7.3600e+00  1.5590e+01
  3.4060e+01  3.5500e+01  8.4000e+01  2.8500e+01  1.6060e+01  1.0560e+01
  2.6170e+01  1.5880e+01  2.9000e+00  1.9460e+01  1.4930e+01  6.4800e+00
  1.9440e+01  8.5500e+01  1.5290e+01  7.3000e+00  1.1560e+01  9.7500e+00
  1.6390e+01  2.4600e+01  1.2780e+01  1.7940e+01  2.2360e+01  1.5020e+01
  1.8690e+01  2.0100e+01  6.6600e+00  8.3000e+00  2.1560e+01  2.0250e+01
  1.1540e+01  1.2200e+01  8.7500e+01  2.5350e+01  1.8200e+01  2.3270e+01
  4.2500e+01  1.9170e+01  1.1600e+01  9.8900e+00  9.4500e+00  3.6700e+01
  2.0380e+01  8.5600e+00  1.7140e+01  1.7310e+01  6.1400e+00  7.0576e+02
  2.1090e+01  4.7600e+00 -1.5250e+01  1.9010e+01  1.4940e+01  5.9100e+00
  1.3040e+01  2.1750e+01  1.9640e+01  2.3610e+01  5.3000e+00  2.9780e+01
  4.9920e+01  1.2700e+00  1.6200e+01  1.1040e+01  2.3460e+01  2.7780e+01
  1.0000e-01  1.8590e+01  1.6380e+01  3.3750e+01  1.8050e+01  2.5800e+01
  1.6180e+01  9.3000e+00  1.7670e+01  2.0220e+01  2.3900e+01  2.5320e+01
  3.2880e+03  1.6280e+01  8.7900e+00  1.7510e+01  1.6520e+01  6.3000e-01
  8.0000e+01  5.8200e+00  2.7060e+01  8.0760e+01  1.2400e+01  1.2880e+01
  1.4960e+01  2.1150e+01  1.7780e+01  3.8500e+01  1.1060e+01  1.8580e+01
  2.4400e+01  4.0760e+01  2.0910e+01  2.5520e+01  7.6400e+00  1.3910e+02
  3.0220e+01  2.1860e+01  5.4300e+00  2.8470e+01  1.1250e+01  5.5500e+01
  1.1550e+01  4.4000e+00  1.0100e+01  1.6570e+01  3.0700e+01  6.7400e+00
  1.5260e+01  3.7000e+01  1.0640e+01  2.3760e+01  3.1900e+01  4.0020e+01
  2.0090e+01  4.1520e+01  5.0600e+00  4.7500e+01  4.3300e+00  1.8080e+01
  9.5000e+01  2.1500e+00  5.1000e+01  2.3800e+01  1.6850e+01  1.2900e+00
  2.7260e+01  8.1050e+02  4.3020e+01  5.5840e+01  1.7000e+00  2.8600e+00
  2.4200e+01  6.2000e+01  1.3180e+01  8.9600e+00  3.3500e+01  1.8710e+01
  3.1280e+01  2.5300e+01  8.7760e+01  9.9000e+01  1.4640e+01  1.9899e+02
  2.7760e+01  2.1300e+01  2.7520e+01  2.3280e+01  1.7530e+01  2.2100e+01
  1.4780e+01  7.7500e+00  2.4910e+01  7.6200e+00  9.0800e+00  2.2000e+00
  1.4500e+00  7.6600e+00  6.3700e+00  1.1610e+01  2.7800e+01  5.1600e+00
  1.4830e+01  1.7520e+01  2.3640e+01  1.9380e+01  3.8020e+01  4.5900e+00
  2.1510e+01  1.7440e+01  1.2540e+01  3.9400e+01  1.9760e+01  2.6600e+01
  1.4590e+01  1.8490e+01  4.3000e+00  2.3160e+01  3.9000e+01  1.4310e+01
  1.7620e+01  4.1200e+01  4.2520e+01  1.5960e+01  6.7900e+00  8.0000e-01
  5.8100e+00  4.8860e+01  3.1520e+01  1.2310e+01  1.7890e+01  2.9600e+00
  1.3240e+01  8.5100e+00  2.7960e+01  1.1950e+01  5.9700e+00  4.3100e+00
  2.7200e+01  2.9010e+01  1.6540e+01  8.7800e+00  4.8600e+00  2.2600e+01
  2.2090e+01  1.7550e+01  3.4680e+01  2.0830e+01  1.2000e+00  2.1900e+01
  7.8500e+00  7.0200e+00 -7.0000e+01  7.0000e+01  3.9700e+01  1.0510e+01
  5.8300e+00  1.9950e+01  1.6590e+01  4.6500e+01  1.8150e+01  2.0520e+01
  4.7500e+00  4.1020e+01  1.8630e+01  2.1700e+01  3.0520e+01  1.7060e+01
  3.2760e+01  4.0000e-02  3.0000e-02  2.0150e+01  2.5770e+01  4.6080e+01
  2.8760e+01  4.7800e+01  4.7000e+00  1.8230e+01  1.5280e+01  7.6000e+00
  1.4160e+01  3.3780e+01  1.5480e+01  1.4760e+01  1.9660e+01  1.0800e+01
  4.6000e-01  3.5540e+01  1.3840e+01  7.5300e+00  2.3470e+01  2.4780e+01
  3.7520e+01  2.2350e+01  2.7400e+01  1.3350e+01  6.0760e+01  7.8600e+00
  8.7500e+00  3.0550e+01  4.0520e+01  2.1600e+01  6.7800e+00  1.0750e+01
  5.9900e+00 -5.6600e+00  2.7800e+00  3.6240e+01  1.7010e+01  7.9500e+00
  1.8540e+01  7.8900e+00  1.4860e+01  3.1490e+01  1.3590e+01  3.7280e+01
  3.6260e+01  2.7320e+01  1.4240e+01  5.8800e+00  4.1000e+01  7.8000e+00
  5.2000e+01  2.1020e+01  5.6900e+00  2.6200e+00]
improvement_surcharge [ 0.3 -0.3  0.   0.6]
total_amount [  9.95  16.3    5.8  ... 230.81 128.68 117.12]
congestion_surcharge [nan 0.  2.5]

In [5]:
df[['tpep_pickup_datetime','tpep_dropoff_datetime']] = df[['tpep_pickup_datetime','tpep_dropoff_datetime']].apply(pd.to_datetime, errors = 'coerce')

In [6]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   int64
trip_distance                   float64
RatecodeID                        int64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
dtype: object